// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Ninja",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Ninja",
            targets: ["AppModule"],
            bundleIdentifier: "com.gameofapps.Ninja",
            teamIdentifier: "7G7257RM8J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "This sample app uses the camera.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
              .process("Resources"),
              .copy("Models")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
